development:
  clients:
    default:
      database: authenticating_proxy_development
      hosts:
        - <%= ENV.fetch("MONGODB_URI", "localhost:27017") %>

test:
  clients:
    default:
      database: authenticating_proxy_test
      hosts:
        - <%= ENV.fetch("MONGODB_URI", "localhost:27017") %>
      options:
        read:
          mode: :primary

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
      options:
        write:
          w: majority
        read:
          mode: :primary_preferred
