development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI", "mongodb://localhost:27017/authenticating_proxy_development") %>

test:
  clients:
    default:
      uri: <%= ENV.fetch("TEST_MONGODB_URI", "mongodb://localhost:27017/authenticating_proxy_test") %>
      options:
        read:
          mode: :primary

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
      options:
        write:
          w: majority
        read:
          mode: :primary_preferred
