# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2107cc6edf5849d66c21f3ddd21128a8bd2bef86b526642ba47f9e73a30fc31c658b9d2f580340aa5b7779bc1e7c6c72775bb85bb665e1679a94a57fd9a7f73

test:
  secret_key_base: 8bd9f9774d46e23b859c99145db3fa718a55d1acbeaeffefbeba5b1df0bfeecd8c0b5f56a29d640fa8a2a0dda08865662b44b2e47f505d11bfb97b183e4c9a61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
